"""Add FlowerPrice column to flowers table

Revision ID: 25a08d2bf49b
Revises: e338e3a4e3eb
Create Date: 2024-12-18 07:29:10.007612

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '25a08d2bf49b'
down_revision = 'e338e3a4e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flowers', sa.Column('FlowerPrice', sa.Integer(), nullable=False), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flowers', 'FlowerPrice', schema='my_app_schema')
    # ### end Alembic commands ###
