"""Add FlowerPrice column to flowers table

Revision ID: a88690c5ecda
Revises: 25a08d2bf49b
Create Date: 2024-12-18 07:32:03.870155

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'a88690c5ecda'
down_revision = '25a08d2bf49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
