"""create providerFlowers table

Revision ID: e338e3a4e3eb
Revises: 6467658d1b05
Create Date: 2024-11-20 04:12:22.438455

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'e338e3a4e3eb'
down_revision = '6467658d1b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
